/* ===========================================================
   Keystone Lens — the adaptive briefing layer.
   The reader chooses their seat (Leadership / Risk / Technology
   / Client) and the page re-briefs itself: per-section "through
   your lens" callouts, a recommended five-stop path, and a
   persona signal the briefing agent picks up. Also remembers
   where a returning reader left off and offers to resume.
   All progressive enhancement: no JS → the page is unchanged.
   =========================================================== */
(function(){
  const reduce = matchMedia('(prefers-reduced-motion: reduce)').matches;
  const still = () => reduce || document.body.classList.contains('no-anim');

  const PERSONAS = {
    general: { label: 'General briefing', short: 'General' },
    exec:    { label: 'Leadership & Strategy', short: 'Leadership' },
    risk:    { label: 'Risk & Independence',   short: 'Risk' },
    tech:    { label: 'Technology & Engineering', short: 'Technology' },
    client:  { label: 'Client & Market', short: 'Client' },
  };

  /* per-section, per-persona briefing notes — authored inference, executive tone */
  const NOTES = {
    whynow: {
      exec: 'The exposure is not missing AI — EY has AI. It is owning none of the layer those investments will run on. Read the peer moves as the market pricing the window.',
      risk: 'Whoever owns the systems layer sets the control standards everyone else inherits. Running downstream means accepting someone else’s risk model — that is the governance stake in this section.',
      tech: 'The named gap is infrastructure, not applications: platforms and agents exist, but no governed runtime and certification layer makes them composable across the firm.',
      client: 'For a regulated enterprise this is the “why EY” section: the advisor whose AI arrives governed by design, with the evidence to show a regulator — not governed by promise.',
    },
    futures: {
      exec: 'The null hypothesis has a price. “Wait” quietly resolves to “rent, later, at a premium” — that repricing is the strategic content of this board.',
      risk: 'Renting the layer means inheriting someone else’s control model and evidence store. That is an independence and defensibility problem before it is a margin problem.',
      tech: 'Owning the layer is what makes primitives reusable. Renting means rebuilding controls per platform, per engagement, forever.',
      client: 'Clients inherit the posture EY chooses: governed on EY’s substrate, or reassembled per engagement on rented runtimes.',
    },
    keystone: {
      exec: 'Four nouns you can inspect: the Lab, the OS, the Gate, the Proving Ground. The 90-day ask depends on nothing else on this page.',
      risk: 'The Gate is the control objective made structural — certification happens before operation, so independence review precedes deployment instead of following discovery.',
      tech: 'Architecturally: the Lab is the delivery organization, the OS is the runtime, the Gate is the trust pipeline, and the Proving Ground is staged rollout on governed data.',
      client: 'You touch three of the four: experiment in the Proving Ground, run on the OS, and inherit systems that cleared the Gate.',
    },
    keystoneos: {
      exec: 'This is the compounding asset. Environments, not engagements — each one is reusable, so delivery cost falls while the library grows.',
      risk: 'Policy, controls, and evidence are versioned code, which means audit trails are generated by the runtime — not reconstructed after the fact.',
      tech: 'Environment-as-code across nine layers, compiled into a running estate with synthetic customers and resident adversaries. This is the section to stress-test.',
      client: 'Your enterprise, compiled: agents are tested against a living model of your policies and customers before anything touches production.',
    },
    intel: {
      exec: 'The deck you would actually run the venture from: readiness, value against baseline, and posture — computed from evidence, not compiled the night before the meeting.',
      risk: 'Exceptions, control fires, and red-team outcomes stream with lineage. Supervision becomes continuous instead of periodic.',
      tech: 'There is no separate metric store to drift out of sync — every figure derives from the sealed evidence ledger, so the dashboard cannot disagree with the audit trail.',
      client: 'The same instruments extend to your estate: your board sees governed-agent posture with the same evidence discipline EY runs on itself.',
    },
    trust: {
      exec: 'The moat. Peers demonstrate agents; none can certify them under independence constraints. That certification capability is the defensible asset.',
      risk: 'Your section. Every risk row maps to a runtime control, certification issues a revocable passport, and an independent board clears every one.',
      tech: 'A six-station pipeline: identity → evaluation → independence → red-team → attestation → passport. Run the certification below and watch the stations clear.',
      client: 'This is what you show your regulator: a passported agent with sealed evidence, full lineage, and a certification you can inspect.',
    },
    lighthouse: {
      exec: 'Contained proof: three workflows, named buyers, measurable targets — enough to inform scale-or-stop, small enough to cap regret.',
      risk: 'Banking first because the constraints are hardest. If the governance holds under banking scrutiny, it holds anywhere.',
      tech: 'Three demonstrators, one substrate: the same identity, evaluation, and evidence primitives run under each — that shared layer is what is actually being proven.',
      client: 'Real pains with numbers attached: third-party risk cycle time, agent control testing, SOC triage. Targets you can hold the Lab to.',
    },
    build: {
      exec: 'The operating-model answer to “why will this stick”: forward-deployed teams, reskilled people, and EY as its own first proving ground.',
      risk: 'Note the sequence — EY runs Keystone on itself before any client. Trust becomes infrastructure before it becomes a product.',
      tech: 'The seven-step loop is the delivery method: embed in the workflow, rebuild the process around the agent, and componentize what works.',
      client: 'Your teams keep the capability after the engagement — supervisors trained, processes redesigned, systems governed. Uplift is the deliverable.',
    },
    whyjohn: {
      exec: 'The operator search is the real execution risk in a venture like this. This section argues fit by trajectory, not biography.',
      risk: 'An operator formed by intelligence work and banking AI security treats adversaries and independence as the environment — not as compliance theater.',
      tech: 'Built agentic product end to end; holds the architecture conversation and the C-suite conversation without translation loss.',
      client: 'The person your CRO and CISO will actually be in the room with — fluent in both their languages.',
    },
    decision: {
      exec: 'The ask, priced: six yes-or-no gates at day 90. Flip the board below and watch the verdict compute.',
      risk: 'Gate v1 cleared by Independence and Risk is a precondition, not a milestone. Governance leads the build here.',
      tech: 'What must be live by day 90: one governed agent, in a sandbox, on governed data, measured against a manual baseline — an integration test for the whole thesis.',
      client: 'Client demand sits inside the proof, not after it: two lighthouse banks in named conversations, one signed sandbox LOI.',
    },
    ask: {
      exec: 'Option staging: each phase buys information before capital scales. Commit to a stage, see the proof, open the next.',
      risk: 'Nothing scales until the layer beneath it is certified — the growth model and the control model are the same model.',
      tech: 'Phase 2 is where the primitives — the router, the eval harness, the simulation lab — become cross-domain infrastructure.',
      client: 'Banking proves it in six to nine months. Your industry’s environment is the reusable output of the phase after.',
    },
    nolose: {
      exec: 'The board answer: limited downside, measured upside, reusable assets, clear exit ramps. Not an innovation spend — a staged strategic option.',
      risk: 'Even the stop scenario leaves EY holding the governance IP: the Gate methodology, the control models, and the delivery playbooks.',
      tech: 'The fallback assets are technical too — certified control packs, eval harnesses, and reference architecture survive any early stop.',
      client: 'If it stops early, you still keep a governance assessment, a workflow value map, and an AI control blueprint on your own data.',
    },
  };

  const PATHS = {
    exec:   [['whynow','Why now'],['keystone','The four things'],['futures','Three futures'],['decision','The 90-day proof'],['ask','The scale path']],
    risk:   [['trust','The Gate, in depth'],['keystoneos','The OS · controls as code'],['intel','The intelligence layer'],['decision','The 90-day proof'],['nolose','The no-lose staging']],
    tech:   [['keystoneos','The OS · environment as code'],['truth','The Truth Layer'],['intel','The intelligence layer'],['lab','Inside the Lab'],['products','Frontier to system']],
    client: [['lighthouse','The banking proof'],['adoption','How the market engages'],['trust','The Gate, in depth'],['intel','The intelligence layer'],['decision','The 90-day proof']],
  };

  let lens = 'general';
  try{ const saved = localStorage.getItem('ksLens'); if(saved && PERSONAS[saved]) lens = saved; }catch(e){}
  /* ?lens= deep link wins over the saved choice — lets a forwarded link say "read this as Risk" */
  try{
    const q = new URLSearchParams(location.search).get('lens');
    if(q && PERSONAS[q]) lens = q;
  }catch(e){}

  /* ---------- public surface for the briefing agent ---------- */
  window.KeystoneLens = { get(){ return { id: lens, label: PERSONAS[lens].label }; } };
  const announce = () => { try{ dispatchEvent(new CustomEvent('keystone:lens', { detail: window.KeystoneLens.get() })); }catch(e){} };

  /* ---------- UI scaffold ---------- */
  const root = document.createElement('div'); root.id = 'klens';
  root.innerHTML =
    '<button class="klens-fab" id="klensFab" aria-expanded="false" aria-controls="klensPanel">' +
      '<span class="klens-gem" aria-hidden="true">◈</span><span class="klens-fab-t">Lens · <b id="klensCur">General</b></span>' +
    '</button>' +
    '<div class="klens-panel" id="klensPanel" role="dialog" aria-label="Choose your briefing lens">' +
      '<div class="klens-t">Read this pitch from your seat</div>' +
      '<div class="klens-s">The page adapts its callouts — and the briefing agent answers in your language.</div>' +
      '<div class="klens-opts" id="klensOpts" role="group" aria-label="Briefing lens"></div>' +
      '<div class="klens-path" id="klensPath" hidden>' +
        '<div class="klens-pl">Your five-stop path</div><ol id="klensPathList"></ol>' +
      '</div>' +
    '</div>';
  document.body.appendChild(root);

  const fab = root.querySelector('#klensFab'), panel = root.querySelector('#klensPanel'),
        cur = root.querySelector('#klensCur'), opts = root.querySelector('#klensOpts'),
        pathBox = root.querySelector('#klensPath'), pathList = root.querySelector('#klensPathList');

  Object.keys(PERSONAS).forEach(id => {
    const b = document.createElement('button');
    b.className = 'klens-opt'; b.dataset.lens = id;
    b.setAttribute('aria-pressed', 'false');
    b.textContent = PERSONAS[id].label;
    b.addEventListener('click', () => { setLens(id); });
    opts.appendChild(b);
  });

  function openPanel(){ panel.classList.add('open'); fab.setAttribute('aria-expanded','true'); }
  function closePanel(){ panel.classList.remove('open'); fab.setAttribute('aria-expanded','false'); }
  fab.addEventListener('click', () => panel.classList.contains('open') ? closePanel() : openPanel());
  addEventListener('keydown', e => { if(e.key === 'Escape' && panel.classList.contains('open')) closePanel(); });
  addEventListener('pointerdown', e => {
    if(panel.classList.contains('open') && !root.contains(e.target)) closePanel();
  }, { passive: true });

  /* ---------- lens notes injected per section ---------- */
  const noteEls = {};
  function applyNotes(){
    Object.keys(NOTES).forEach(secId => {
      const text = lens === 'general' ? null : NOTES[secId][lens];
      let el = noteEls[secId];
      if(!text){ if(el){ el.remove(); delete noteEls[secId]; } return; }
      if(!el){
        const sec = document.getElementById(secId); if(!sec) return;
        const anchor = sec.querySelector('.wrap .lead') || sec.querySelector('.wrap .h2'); if(!anchor) return;
        el = document.createElement('aside');
        el.className = 'lens-note';
        el.innerHTML = '<span class="ln-k" aria-hidden="true">◈</span><div><span class="ln-l"></span><p></p></div>';
        anchor.insertAdjacentElement('afterend', el);
        noteEls[secId] = el;
      }
      el.querySelector('.ln-l').textContent = 'Through the ' + PERSONAS[lens].label + ' lens';
      el.querySelector('p').textContent = text;
      el.classList.remove('in');
      if(still()){ el.classList.add('in'); }
      else { requestAnimationFrame(() => requestAnimationFrame(() => el.classList.add('in'))); }
    });
  }

  function renderPath(){
    if(lens === 'general' || !PATHS[lens]){ pathBox.hidden = true; pathList.innerHTML = ''; return; }
    pathBox.hidden = false; pathList.innerHTML = '';
    PATHS[lens].forEach(([id, label]) => {
      const li = document.createElement('li');
      const a = document.createElement('a'); a.href = '#' + id; a.textContent = label;
      a.addEventListener('click', () => closePanel());
      li.appendChild(a); pathList.appendChild(li);
    });
  }

  function setLens(id){
    lens = id;
    try{ localStorage.setItem('ksLens', id); }catch(e){}
    document.body.dataset.lens = id;
    cur.textContent = PERSONAS[id].short;
    opts.querySelectorAll('.klens-opt').forEach(b => {
      const on = b.dataset.lens === id;
      b.classList.toggle('on', on);
      b.setAttribute('aria-pressed', on ? 'true' : 'false');
    });
    renderPath();
    applyNotes();
    announce();
  }
  setLens(lens);

  /* ---------- remember where the reader left off ---------- */
  const SECS = [...document.querySelectorAll('section.sec[id]')];
  function currentSec(){
    const mid = innerHeight * 0.45;
    for(const s of SECS){ const r = s.getBoundingClientRect(); if(r.top <= mid && r.bottom >= mid) return s; }
    return null;
  }
  let saveT = 0;
  addEventListener('scroll', () => {
    clearTimeout(saveT);
    saveT = setTimeout(() => {
      const s = currentSec();
      if(s && SECS.indexOf(s) > 1){ try{ localStorage.setItem('ksResume', s.id); }catch(e){} }
    }, 900);
  }, { passive: true });

  (function offerResume(){
    let saved = null; try{ saved = localStorage.getItem('ksResume'); }catch(e){}
    if(!saved || scrollY > 120 || location.hash) return;
    const sec = document.getElementById(saved); if(!sec) return;
    const tag = sec.querySelector('.kick .tag');
    const title = tag ? tag.textContent.replace(/^Supporting detail · /i, '') : saved;
    const toast = document.createElement('div');
    toast.className = 'klens-toast'; toast.setAttribute('role', 'status');
    toast.innerHTML = '<span class="kt-t">This device left off at <b></b></span>' +
      '<button class="kt-go">Resume ↓</button><button class="kt-x" aria-label="Dismiss">×</button>';
    toast.querySelector('b').textContent = title;
    document.body.appendChild(toast);
    const kill = () => { toast.classList.remove('in'); setTimeout(() => toast.remove(), 400); };
    toast.querySelector('.kt-go').addEventListener('click', () => {
      const top = sec.getBoundingClientRect().top + scrollY - 70;
      scrollTo({ top, behavior: still() ? 'auto' : 'smooth' });
      kill();
    });
    toast.querySelector('.kt-x').addEventListener('click', kill);
    setTimeout(() => toast.classList.add('in'), still() ? 0 : 1400);
    setTimeout(kill, 16000);
  })();
})();
